### PR TITLE
SUP-34435 Save XMP metadata in canonical format for PDF/A documents.

### PR DESCRIPTION
**Pull request by carl-di-ortus**
This fixes a support issue described at https://jira.itextsupport.com/browse/SUP-34435

XMP metadata saved in canonical format had some issues generating invalid namespace attributes with empty namespace. To prevent empty namespace a simple check is added to XMPSerializerRdf.DeclareNamespace().

Also a new protected property is introduced in PdfDocument called serializeOptions. Property is needed because if users were to call SetXmpMetadata() with certain options it might get overwritten on document close.

### CODE REVIEW

**Comment by vismabsc** [comment]
When will this be merged?

**Comment by yulian-gaponenko** [comment]
Hi @carl-di-ortus @vismabsc 
Thank you for the Pull Request! First of all, do you mind signing our Contributor License Agreement and send it back to us? The details are available at https://itextpdf.com/en/how-buy/legal/itext-contributor-license-agreement , it's required for us to proceed with merging your changes to the main code base.

After that it still might take some time before we will be able to pick it up to perform some maintenance work (making sure java/c# versions are synced, adding additional tests) and to merge it.

**Comment by carl-di-ortus** [comment]
I'd love to help writing a test for it, but I'm afraid I don't understand your tests logic. I've run all tests on Visual Studio test runner, and while hundreds of them passed, also hundreds of them failed. I'm not used to having any failed tests in project before adding new tests.

**Comment by vismaaddo** [comment]
Please merge this ... we're eagerly waiting on the fix.

**Pull request closed without merging**
