### PR TITLE
Updated licenses terms

### PR DESCRIPTION
**Pull request by johnvpetersen**
Updated the license terms in a manner that is consistent with the terms and conditions in the AGPL. I have engaged in several dialogs with iText management and legal counsel. The revised text avoids any misrepresentations of what the AGPL actually requires and thereby, ameliorates the risk of non-enforceability.

### CODE REVIEW

**Comment by avlemos** [comment]
Thank you for your contribution @johnvpetersen. We have now clarified our LICENSE.md file, as you can see in our 8ef10dd commit. Thank you for raising the issue.

**Comment by cloudhan** [comment]
https://github.com/itext/itext7-dotnet/blob/3aef486f95c5cca8358e61140535d7f7c67590fb/itext/itext.kernel/itext/kernel/VersionInfo.cs#L29-L31

It still present in this file.

**Comment by cloudhan** [comment]
@avlemos the commit does not change licence header in every file, which makes the LICENSE.md different from the source files.

**Comment by avlemos** [comment]
@cloudhan, right now what we have is a hook which will update every file once they get _touched_ (so, on every ADD and COMMIT).

**Pull request closed without merging**
